In [1]:
import numpy as np

In [2]:
myPythonList = [1,9,8,3]
print(myPythonList)

[1, 9, 8, 3]


In [3]:
numpy_array_from_list = np.array(myPythonList)
numpy_array_from_list


array([1, 9, 8, 3])

In [4]:
a  = np.array([1,9,8,3])
print(a)

[1 9 8 3]


In [5]:
x=numpy_array_from_list + 10
print(x)

[11 19 18 13]


In [6]:
a  = np.array([1,2,3])
print(a.shape)
print(a.dtype)


(3,)
int64


In [7]:
#### Different type
b  = np.array([1.1,2.0,3.2])
print(b.dtype)

float64


In [8]:
### 2 dimension
c = np.array([(1,2,3),
              (4,5,6)])
print(c)

[[1 2 3]
 [4 5 6]]


In [9]:
### 3 dimension
d = np.array([
    [[1, 2,3],
        [4, 5, 6]],
    [[7, 8,9],
        [10, 11, 12]]
])
print(d.shape)
(2, 2, 3)
print(d)

(2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [10]:
import numpy as np
x=np.zeros((2,2), dtype=np.int16)
print(x)

[[0 0]
 [0 0]]


In [11]:
import numpy as np
y=np.ones((1,2,3), dtype=np.int16)
print(y.shape)	
print(y)

(1, 2, 3)
[[[1 1 1]
  [1 1 1]]]


In [12]:
import numpy as np
e  = np.array([(1,2,3), (4,5,6)])
print(e)
e.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
e.flatten()


array([1, 2, 3, 4, 5, 6])

In [14]:
## Horitzontal Stack
import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Horizontal Append:', np.hstack((f, g)))

Horizontal Append: [1 2 3 4 5 6]


In [15]:
## Vertical Stack
import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Vertical Append:', np.vstack((f, g)))

Vertical Append: [[1 2 3]
 [4 5 6]]


In [16]:
## Generate random nmber from normal distribution
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)			


[5.26857818 4.08331211 4.93464732 5.23358022 5.69064506 5.40321734
 4.89438118 5.86704765 4.74514979 5.70491739]


In [17]:
A = np.matrix(np.ones((4,4)))		
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [18]:
np.asarray(A)[2]=2
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [1. 1. 1. 1.]]


In [19]:
np.arange(1, 11)	

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
np.arange(1, 14, 4)	

array([ 1,  5,  9, 13])

In [21]:
import numpy as np
np.linspace(1.0, 10.0, num=20)


array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [22]:
np.linspace(1.0, 5.0, num=5, endpoint=False)

array([1. , 1.8, 2.6, 3.4, 4.2])

In [23]:
np.logspace(3.0, 4.0, num=4)

array([ 1000.        ,  2154.43469003,  4641.58883361, 10000.        ])

In [24]:
x = np.array([1,2,3], dtype=np.complex128)
x.itemsize	

16

In [25]:
## Slice
import numpy as np
e  = np.array([(4,5,6), (7,8,9)])
print(e)


[[4 5 6]
 [7 8 9]]


In [26]:
## First column
print('First row:', e[0])

## Second col
print('Second row:', e[1])

First row: [4 5 6]
Second row: [7 8 9]


In [27]:
print('Second column:', e[:,1])	

Second column: [5 8]


In [28]:
## Second Row, two values
print(e[1, :2])

[7 8]


In [29]:
#Second column 2 values
print(e[:2,1])

[5 8]


In [30]:
import numpy as np
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)	

[5.81838101 5.7165292  5.52759818 5.02827147 5.60862873 4.40137324
 4.92277897 5.38988724 4.76215278 4.50678734]


In [31]:
### Min 
print(np.min(normal_array))

### Max 
print(np.max(normal_array))

### Mean 
print(np.mean(normal_array))

### Median
print(np.median(normal_array))

### Sd
print(np.std(normal_array))

4.401373235587653
5.8183810093892365
5.168238814542006
5.209079353093663
0.48640166665779133


In [32]:
## Linear algebra
### Dot product: product of two arrays
f = np.array([1,2])
g = np.array([4,5])
### 1*4+2*5
np.dot(f, g)

14

In [33]:
### Matmul: matruc product of two arrays
h = [[1,2],[3,4]] 
i = [[5,6],[7,8]] 
### 1*5+2*7 = 19
np.matmul(h, i)

array([[19, 22],
       [43, 50]])

In [34]:
# Taking a 3 * 3 matrix
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
  
# Calculating the inverse of the matrix
print(np.linalg.inv(A))

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [35]:
# creating a 2X2 Numpy matrix
n_array = np.array([[50, 29], [30, 44]])
  
# Displaying the Matrix
print("Numpy Matrix is:")
print(n_array)
  
# calculating the determinant of matrix
det = np.linalg.det(n_array)
  
print("\nDeterminant of given 2X2 matrix:")
print(int(det))

Numpy Matrix is:
[[50 29]
 [30 44]]

Determinant of given 2X2 matrix:
1330


In [36]:
# Let's create a square matrix (NxN matrix)
mx = np.array([[1,1,1],[0,1,2],[1,5,3]])

# Let's get rank of matrix 
np.linalg.matrix_rank(mx)


3

In [37]:
example_matrix = np.array([
  [1,2,3,4],
  [5,6,7,8],
  [9,10,11,12],
  [13,14,15,16]
])
eigenvalues, eigenvectors = np.linalg.eig(example_matrix)
print(eigenvalues, eigenvectors)

[ 3.62093727e+01 -2.20937271e+00 -2.62410379e-15 -9.51420961e-17] [[-0.15115432 -0.72704996 -0.47688035 -0.07702174]
 [-0.34923733 -0.28320876  0.83665151 -0.30149603]
 [-0.54732033  0.16063243 -0.24266197  0.83405728]
 [-0.74540333  0.60447363 -0.11710919 -0.45553951]]


In [38]:
# make matrix with numpy
gfg = np.matrix('[6, 2; 3, 4]')
         
# applying matrix.diagonal() method
diag = gfg.diagonal()
   
print(diag)

[[6 4]]


In [39]:
# make matrix with numpy
gfg = np.matrix('[4, 1; 12, 3]')
              
# applying matrix.transpose() method
trans = gfg.transpose()
    
print(trans)

[[ 4 12]
 [ 1  3]]


In [40]:
# make matrix with numpy
gfg = np.matrix('[4, 1; 12, 3]')
              
# applying matrix.trace() method
tracem = gfg.trace()
    
print(tracem)

[[7]]
